# Generated by Django 6.0.7 on 2026-07-12 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_name', models.CharField(max_length=200)),
                ('region', models.CharField(default='Europe', max_length=100)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('critical', 'Critical')], default='healthy', max_length=20)),
                ('expected_viewers', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StreamMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('region', models.CharField(max_length=100)),
                ('concurrent_viewers', models.PositiveIntegerField(default=0)),
                ('buffer_ratio', models.FloatField(default=0)),
                ('startup_time_ms', models.FloatField(default=0)),
                ('cdn_latency_ms', models.FloatField(default=0)),
                ('failure_rate', models.FloatField(default=0)),
                ('bitrate_kbps', models.FloatField(default=0)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='streams.stream')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
