# Generated by Django 6.0.7 on 2026-07-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='stream_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='streammetric',
            name='fps',
            field=models.FloatField(default=30),
        ),
        migrations.AddField(
            model_name='streammetric',
            name='packet_loss',
            field=models.FloatField(default=0),
        ),
    ]
