# Generated by Django 6.0.7 on 2026-07-13 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_stream_stream_url_streammetric_fps_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stream',
            options={'ordering': ['-created_at']},
        ),
    ]
