# Generated by Django 6.0.7 on 2026-07-13 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_knowledgedocument_incident_incident_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgedocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['-created_at']},
        ),
    ]
